import type { Content } from './en'

type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }

// 日本語 — prominent strings; the rest fall back to English.
const ja: DeepPartial<Content> = {
  brand: { affiliate: 'ロッテローミング' },
  nav: { home: 'ホーム', browse: '旅行', applications: '申込履歴', login: 'ログイン', myAccount: 'アカウント' },
  cta: {
    browse: '韓国プランを見る',
    global: '他の国へ？ グローバルプラン',
    selectDestination: '渡航先を選ぶ',
    apply: '申し込む',
    viewDetail: '詳細を見る',
    continue: '続ける',
    next: '次へ',
    submit: '申し込む',
    toComplete: '申し込みを行う',
    goHome: 'ホームへ',
    viewApplication: '申込を見る',
    activate: '開通ガイド',
    retry: 'もう一度',
  },
  home: {
    heroEyebrow: '韓国の旅のデータ',
    heroTitle: 'あなたの韓国を、\nすぐにつなぐ。',
    heroDesc: '訪韓旅行者向けのプリペイド eSIM・USIM。数分で開通・契約なし、L.POINT 会員特典付き。',
    plansTitle: '韓国データプラン',
    plansDesc: 'プランを選んで数分でお申し込み。',
    benefitsTitle: 'L.POINT 会員特典',
    benefitsDesc: 'LOTTE ROAMING のお申し込みでこの特典が付きます。',
    destinationsMore: 'すべて見る',
    howTitle: 'ご利用方法',
    howSteps: [
      { title: 'プランを選択', desc: 'デイリーかボリュームを旅程に合わせて。' },
      { title: 'オプション選択', desc: 'eSIM か USIM、日数と回線。' },
      { title: '情報を入力', desc: '受け取り方法とお客様情報。' },
      { title: '到着後に開通', desc: 'データをオンにすれば完了。' },
    ],
    faqTitle: 'よくある質問',
  },
  browse: {
    title: '韓国データプラン',
    subtitle: '訪韓旅行者向けのプリペイド eSIM・USIM。',
    resultCount: (n: number) => `${n} 件のプラン`,
    empty: '利用できるプランがありません。',
    koreaName: '韓国',
  },
  product: {
    perDay: '1日あたり',
    days: '日数',
    total: '総データ量',
    validity: '有効期間',
    sim: 'SIM',
    network: '回線',
    benefitsTitle: '付帯特典',
    noticeTitle: 'ご注意',
    priceNote: '参考料金 · 日数・容量により異なります。',
    perDayShort: '日',
    unlimited: '無制限',
    daysUnit: (n: number) => `${n} 日`,
    gbPerDay: (n: number) => `1日 ${n}GB`,
    totalGb: (n: number) => `合計 ${n}GB`,
  },
  sim: { esimDesc: 'QRで即インストール・物理カードなし', usimDesc: '物理カード・出発前に配送' },
  network: { roaming: 'ローミング回線', local: 'SKT 現地回線' },
  receive: {
    esim_qr: 'eSIM QR（メール送付）',
    delivery: '宅配（1〜2日）',
    airport_pickup: '空港受取（仁川 T1/T2）',
  },
  steps: ['ログイン', '情報', '確認', '完了'],
  signin: {
    title: 'ログインまたは登録',
    subtitle: 'ワンタップで続行——新規アカウントは L.POINT 会員になります。',
    or: 'または',
    providers: {
      kakao: 'Kakaoで続ける',
      line: 'LINEで続ける',
      google: 'Googleで続ける',
      apple: 'Appleで続ける',
      wechat: 'WeChatで続ける',
      email: 'メールで続ける',
    },
    terms: '利用規約とプライバシーポリシーに同意します（必須）',
    push: '到着ガイド・特典の通知を受け取る',
    marketing: 'マーケティング情報（任意）',
    termsRequired: '必須の規約に同意してください。',
    lpoint: 'アカウント作成で、旅の特典が使える L.POINT メンバーシップも設定されます。',
  },
  applicant: {
    title: '申込情報の入力',
    subtitle: '開通とご案内のため申込者情報を入力してください。',
    name: '氏名',
    email: 'メール',
    phone: '電話番号',
    travelStart: '出発日',
    travelEnd: '帰国日',
    receiveTitle: '受け取り方法',
    address: '配送先住所',
    required: '必須項目です。',
    invalidEmail: 'メール形式が正しくありません。',
    invalidPhone: '10〜11桁の数字を入力してください。',
    invalidDate: '帰国日は出発日以降にしてください。',
    addressRequired: 'USIM 配送先住所を入力してください。',
  },
  confirm: {
    title: '申込内容の確認',
    subtitle: '内容を確認して申し込みを行ってください。',
    destination: '渡航先',
    product: 'プラン',
    options: 'オプション',
    applicant: '申込者',
    period: '旅行日程',
    receive: '受け取り',
    agree: '申込内容とご注意を確認し、同意します。',
    agreeRequired: '同意のうえお進みください。',
    paymentNote: '決済は今後連携予定で、現在は申込受付として進みます。',
    processing: '申込を受付中…',
    estimatedTotal: 'お支払い予定額',
  },
  complete: {
    title: 'お申し込みを受け付けました',
    subtitle: '申込内容と次のご案内をご確認ください。',
    refLabel: '申込番号',
    esimNext: 'eSIM QR をメールでお送りしました。到着後にデータローミングをオンにして開通してください。',
    usimNext: 'USIM はご住所へ配送されます（1〜2日）。出発前にお受け取りください。',
    noticeTitle: 'ご注意',
    summaryTitle: '申込サマリー',
  },
  applications: {
    title: '申込履歴',
    subtitle: 'ローミング申込の状況を確認できます。',
    empty: 'まだ申込はありません。',
    emptyCta: 'ローミングを見る',
    detailTitle: '申込詳細',
    appliedAt: '申込日',
  },
  status: {
    submitted: '受付完了',
    pending_payment: '決済待ち',
    pending_provisioning: '開通準備',
    completed: '開通済み',
    failed: '申込失敗',
    draft: '下書き',
  },
  activate: {
    title: '開通ガイド',
    subtitle: '到着後、以下の手順で開通します。',
    steps: [
      { title: 'eSIM をインストール（QRスキャン）', desc: '受け取った QR をカメラで読み取りインストール。（USIM はカードを挿入）' },
      { title: 'プランを追加', desc: '「eSIM を追加」を押して案内に従います。' },
      { title: 'データローミングをオン', desc: 'LOTTE ROAMING 回線のデータローミングをオンにします。' },
    ],
    done: '開通済みにする',
    help: 'お困りですか？',
  },
  direction: {
    reviewTranslated: '翻訳済み',
    reviewTranslating: '翻訳中…',
    reviewShowOriginal: '原文を表示',
    reviewShowTranslation: '翻訳を表示',
  },
}

export default ja
