import type { Content } from './en'

type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }

// 한국어 — 전체 화면 한국어. (운영/국내 시연용)
const ko: DeepPartial<Content> = {
  brand: { affiliate: '롯데 로밍' },
  nav: { home: '홈', browse: '여행', applications: 'MY', login: '로그인', myAccount: '내 계정', signOut: '로그아웃' },
  cta: {
    browse: '한국 상품 보기',
    global: '다른 나라로? 글로벌 상품',
    selectDestination: '여행지 선택',
    apply: '신청하기',
    viewDetail: '자세히 보기',
    continue: '계속',
    next: '다음',
    submit: '신청 완료',
    toComplete: '신청 접수하기',
    goHome: '홈으로',
    viewApplication: '신청 내역 보기',
    activate: '개통 안내',
    retry: '다시 시도',
    back: '뒤로',
  },
  home: {
    heroEyebrow: '한국 여행 데이터',
    heroTitle: '당신의 한국,\n바로 연결.',
    heroDesc:
      '방한 여행용 선불 eSIM·USIM. 약정 없이 몇 분 만에 개통, L.POINT 멤버십 혜택까지.',
    plansTitle: '한국 데이터 상품',
    plansDesc: '상품을 고르고 몇 분 만에 신청하세요.',
    benefitsTitle: 'L.POINT 멤버십 혜택',
    benefitsDesc: 'LOTTE ROAMING 신청 시 이런 혜택이 함께합니다.',
    destinationsMore: '전체 보기',
    howTitle: '이용 방법',
    howSteps: [
      { title: '상품 선택', desc: '일정에 맞게 데일리 또는 종량제.' },
      { title: '옵션 선택', desc: 'eSIM·USIM, 일수와 연결망.' },
      { title: '정보 입력', desc: '받는 방법과 신청자 정보.' },
      { title: '도착 후 개통', desc: '데이터를 켜면 끝.' },
    ],
    faqTitle: '자주 묻는 질문',
  },
  browse: {
    title: '한국 데이터 상품',
    subtitle: '방한 여행용 선불 eSIM·USIM.',
    resultCount: (n: number) => `상품 ${n}개`,
    empty: '현재 이용 가능한 상품이 없습니다.',
    koreaName: '대한민국',
  },
  builder: {
    title: '내 로밍 맞춤 구성',
    sub: '여행지·유형·용량을 고르면 맞는 상품과 예상 금액을 보여드려요.',
    step1: '여행지',
    step2: '유형',
    step3Daily: '이용 기간',
    dataLabel: '일일 데이터',
    step3Volume: '유효기간',
    daily: '데일리',
    volume: '종량제',
    dailyDesc: '매일 데이터가 새로 채워져요. 매일 꾸준히 쓰기 좋아요.',
    volumeDesc: '정해진 유효기간 동안 총량을 자유롭게 나눠 써요.',
    priceLabel: '예상 금액',
    cta: '상품 보고 신청',
    pickDestination: '여행지를 먼저 선택하세요',
    searchPlaceholder: '여행지 검색',
    noResults: '검색 결과가 없습니다',
  },
  product: {
    perDay: '일 제공량',
    days: '이용 일수',
    total: '총 제공량',
    validity: '유효기간',
    sim: '받는 방식',
    network: '연결 방식',
    coverageGlobal: '전 세계',
    benefitsTitle: '함께 제공되는 혜택',
    noticeTitle: '유의사항',
    priceNote: '예시 요금 · 일정·용량에 따라 달라집니다.',
    perDayShort: '일',
    unlimited: '무제한',
    daysUnit: (n: number) => `${n}일`,
    gbPerDay: (n: number) => `매일 ${n}GB`,
    totalGb: (n: number) => `총 ${n}GB`,
  },
  sim: {
    esimDesc: 'QR로 즉시 설치 · 실물 없음',
    usimDesc: '실물 카드 · 출국 전 배송',
  },
  network: {
    roaming: '로밍망',
    local: 'SKT 현지망',
    roamingDesc: '제휴 통신사 자동 연결 · 도착 즉시',
    localDesc: '한국 현지망 · 도심에서 가장 빠름',
  },
  receive: {
    esim_qr: 'eSIM QR (이메일 발송)',
    delivery: '택배 배송 (1~2일)',
    airport_pickup: '공항 수령 (인천 T1/T2)',
  },
  steps: ['신청 정보', '신청 확인', '완료'],
  signin: {
    title: '로그인 또는 가입',
    subtitle: '한 번에 시작하세요. 신규 가입 시 L.POINT 멤버십이 함께 생성됩니다.',
    or: '또는',
    providers: {
      kakao: '카카오로 계속하기',
      line: 'LINE으로 계속하기',
      google: 'Google로 계속하기',
      apple: 'Apple로 계속하기',
      wechat: 'WeChat으로 계속하기',
      email: '이메일로 계속하기',
    },
    terms: '이용약관 및 개인정보처리방침에 동의합니다 (필수)',
    push: '도착 안내·혜택 알림 받기',
    marketing: '마케팅 정보 수신 (선택)',
    termsRequired: '필수 약관에 동의해 주세요.',
    lpoint: '계정을 만들면 여행 혜택을 위한 L.POINT 멤버십도 함께 설정됩니다.',
    consentTitle: '환영합니다! 마지막 단계예요',
    consentSub: '회원가입 완료를 위해 약관을 확인하고 동의해 주세요.',
    agreeContinue: '동의하고 계속',
    useAnother: '다른 계정으로',
    emailStepTitle: '이메일로 계속',
    emailStepSub: '이메일을 입력하면 로그인 또는 가입으로 이어집니다.',
    emailLabel: '이메일 주소',
    emailPh: 'you@email.com',
    signinStepTitle: '다시 오셨네요',
    signinStepSub: '비밀번호를 입력해 로그인하세요.',
    signupStepTitle: '계정 만들기',
    signupStepSub: '이름과 비밀번호를 설정하면 가입이 완료됩니다.',
    nameLabel: '이름',
    namePh: '이름',
    passwordLabel: '비밀번호',
    passwordPh: '8자 이상',
    confirmLabel: '비밀번호 확인',
    createAccount: '계정 만들기',
    signInBtn: '로그인',
    changeEmail: '이메일 변경',
    backToOptions: '다른 방법으로 로그인',
    pwShort: '8자 이상 입력해 주세요.',
    pwMismatch: '비밀번호가 일치하지 않습니다.',
    passwordRequired: '비밀번호를 입력해 주세요.',
    nameRequired: '이름을 입력해 주세요.',
  },
  applicant: {
    title: '신청 정보 입력',
    subtitle: '개통과 안내를 위해 신청자 정보를 입력해 주세요.',
    name: '신청자 이름',
    namePh: '여권 영문명 또는 한글 이름',
    email: '이메일',
    emailPh: 'example@email.com',
    phone: '휴대폰 번호',
    phonePh: '01012345678',
    travel: '여행 기간',
    travelStart: '출국일',
    travelEnd: '귀국일',
    receiveTitle: '받는 방법',
    address: '배송 주소',
    addressPh: '도로명 주소를 입력하세요',
    required: '필수 입력 항목입니다.',
    invalidEmail: '올바른 이메일 형식이 아닙니다.',
    invalidPhone: '숫자 10~11자리로 입력해 주세요.',
    invalidDate: '귀국일은 출국일 이후여야 합니다.',
    addressRequired: 'USIM 배송을 위해 주소를 입력해 주세요.',
  },
  confirm: {
    title: '신청 확인',
    subtitle: '선택하신 내용을 확인하고 신청을 접수해 주세요.',
    destination: '이용 지역',
    product: '상품',
    options: '옵션',
    applicant: '신청자',
    period: '여행 기간',
    receive: '받는 방법',
    agree: '위 신청 내용과 유의사항을 확인했으며 이에 동의합니다.',
    agreeRequired: '신청 내용 동의가 필요합니다.',
    paymentNote: '결제는 추후 연동 예정이며, 지금은 신청 접수로 진행됩니다.',
    processing: '신청 접수 중…',
    estimatedTotal: '결제 예정 금액',
  },
  complete: {
    title: '신청이 접수되었습니다',
    subtitle: '신청 내역과 다음 안내를 확인하세요.',
    refLabel: '신청번호',
    nextTitle: '다음 단계',
    esimNext: 'eSIM QR이 이메일로 발송되었습니다. 도착 후 데이터 로밍을 켜 개통하세요.',
    usimNext: 'USIM이 입력하신 주소로 배송됩니다(1~2일). 출국 전 수령해 주세요.',
    noticeTitle: '유의사항',
    summaryTitle: '신청 요약',
  },
  applications: {
    title: 'MY 롯데',
    subtitle: '요금제·구독·로밍을 한곳에서 확인하세요.',
    empty: '아직 내역이 없습니다.',
    emptyCta: '요금제·로밍 둘러보기',
    detailTitle: '신청 상세',
    roamingTitle: '로밍',
    appliedAt: '신청일',
  },

  hub: {
    title: '일상에도, 여행에도 모바일',
    subtitle: '집에선 월정액, 여행엔 선불 로밍 — 둘 다 L.POINT 혜택과 함께.',
    note: '시연용 MVP — 확정되지 않은 요금·혜택·약관은 추후 별도 안내됩니다.',
    mvno: {
      eyebrow: '일상',
      title: '요금제 (알뜰폰)',
      desc: 'KT·SKT·LG U+ 망의 무약정 월정액 (LTE·5G).',
      cta: '요금제 보기',
    },
    roaming: {
      eyebrow: '여행',
      title: '여행 로밍',
      desc: '국내외 여행용 선불 eSIM·USIM. 몇 분 만에 개통.',
      cta: '로밍 찾기',
    },
  },

  mvno: {
    catalogTitle: '요금제',
    catalogSub: '국내 주요 통신망의 무약정 월정액(알뜰폰).',
    catalogNote: '예시 요금입니다. 프로모 요금은 초기 개월에 적용되며 혜택은 제공 예정입니다.',
    noResults: '조건에 맞는 요금제가 없습니다.',
    all: '전체',
    techLabel: '망 종류',
    networkLabel: '통신망',
    networkName: { KT: 'KT망', SKT: 'SKT망', LGU: 'LG U+망' },
    perMonth: '월',
    dataLabel: '데이터',
    voiceLabel: '통화',
    smsLabel: '문자',
    unlimited: '무제한',
    min: '분',
    smsUnit: '건',
    smsUnlimited: '문자 무제한',
    callsUnlimited: '통화 무제한',
    detail: '자세히',
    perksTitle: '함께 제공되는 혜택',
    apply: '가입하기',
    priceNote: '예시 월 요금 · 부가세 포함.',
    promoMonths: (n: number) => `프로모 · 첫 ${n}개월`,
    promoFull: (regular: string, months: number) =>
      `첫 ${months}개월 프로모 요금, 이후 월 ₩${regular}.`,
    notices: [
      '무약정 월정액으로, 언제든 위약금 없이 해지할 수 있습니다.',
      '개통을 위해 법적으로 본인확인이 필요합니다.',
      '월 데이터 소진 후에는 다음 달까지 속도가 제한됩니다(요금제별 상이).',
      'eSIM은 지원 단말에서 사용하며, USIM은 개통 전 배송됩니다.',
    ],
    usageTitle: '이번 달',
    lowWarning: '이번 달 데이터가 얼마 남지 않았어요.',
    planLabel: '요금제',
  },

  mvnoStatus: {
    submitted: '접수 완료',
    pending_activation: '개통 준비',
    active: '이용 중',
    failed: '가입 실패',
  },

  subscribe: {
    summaryTitle: '가입 요약',
    infoTitle: '가입자 정보',
    infoSub: '개통을 위해 가입자 정보와 본인확인이 필요합니다.',
    port: '번호',
    portMove: '번호이동',
    portNew: '신규 번호',
    name: '가입자 이름',
    namePh: '신분증상 이름',
    birth: '생년월일',
    phonePort: '이동할 번호',
    phoneNew: '연락처',
    currentCarrier: '현재 통신사',
    currentCarrierPh: '예) SKT / KT / LG U+',
    pay: '결제 수단',
    payCard: '카드',
    payBank: '계좌이체',
    kycTitle: '본인확인',
    kycNote: '개통 전 간단한 본인확인(인증)이 진행됩니다. 시연: 모의 처리.',
    confirmTitle: '확인 후 가입',
    confirmSub: '내용을 확인하고 월 자동결제에 동의해 주세요.',
    firstCharge: '첫 달 결제',
    autopayNote: '자동결제는 모의 처리이며, 지금은 가입 접수로 진행됩니다.',
    agree: '요금제 약관 및 월 자동결제에 동의합니다 (필수).',
    placeCta: '가입하기',
    completeTitle: '가입이 완료되었습니다',
    completeSub: '요금제 개통이 진행 중입니다.',
    subNo: '가입번호',
    esimNext: 'eSIM QR을 이메일로 보내드렸어요. 설치 후 개통을 마치세요.',
    usimNext: 'USIM이 입력하신 주소로 배송됩니다(1~2일). 끼우면 개통됩니다.',
    billingFrom: '다음 청구일',
    viewSub: '구독 보기',
  },

  mySub: {
    title: '내 요금제',
    monthlyFee: '월 요금',
    nextBilling: '다음 청구일',
    activateCta: '개통 완료 처리',
    manageNote: '변경·해지는 고객센터를 통해 제공될 예정입니다.',
  },
  travel: {
    title: '여행',
    subtitle: '어느 여행지든 롯데 혜택과 현지 정보를 둘러보세요.',
    active: '로밍 이용 중',
    preview: '출발 전 미리보기',
    pickPlace: '여행지 변경',
    offersTitle: '이 여행지의 롯데 혜택',
    tipsTitle: '추천',
    phrasesTitle: '여행 회화',
    infoTitle: '알아두면 좋아요',
    tabBenefits: '혜택',
    tabInfo: '정보',
    tabPhrases: '회화',
    tabGuide: '추천',
    empty: '로밍을 시작하면 여행지 혜택이 여기에 표시됩니다.',
    emptyCta: '내 로밍 만들기',
  },

  reminder: {
    upcoming: (d: number) => `출발 D-${d} · 로밍 준비 완료`,
    tomorrow: '내일 출발이에요 · 로밍 준비 완료',
    active: '여행 중 · 로밍 이용 가능',
    cta: '보기',
  },

  usage: {
    title: '데이터 사용량',
    plan: '상품',
    remaining: '남은 용량',
    remainingToday: '오늘 남은 용량',
    used: '사용량',
    usedTotal: '누적 사용량',
    topUp: '데이터 충전',
    lowWarning: '데이터가 얼마 남지 않았어요. 충전하고 계속 연결하세요.',
    expired: '이용 종료',
    dayOf: (d: number, total: number) => `${total}일 중 ${d}일째`,
    daysLeft: (n: number) => `${n}일 남음`,
  },

  phrases: {
    intro: '눌러서 번역하세요. 아래에 직접 입력할 수도 있어요.',
    inputPlaceholder: '번역할 문장을 입력하세요',
    translate: '번역',
    localLabel: '현지어',
    categories: {
      basics: '기본',
      directions: '길찾기',
      dining: '식당',
      shopping: '쇼핑',
      emergency: '긴급',
    },
  },

  info: {
    emergency: '긴급',
    police: '경찰',
    medical: '구급·소방',
    power: '전원·플러그',
    voltage: '전압',
    plugType: '플러그 타입',
    currency: '통화',
    rateNote: '예시 환율이에요. 결제 전 실시간 환율을 확인하세요.',
    localTime: '현지 시각',
    timeDiff: '시차',
    tipping: '팁·매너',
  },
  status: {
    draft: '작성 중',
    submitted: '접수 완료',
    pending_payment: '결제 대기',
    pending_provisioning: '개통 준비',
    completed: '개통 완료',
    failed: '신청 실패',
  },
  statusDesc: {
    submitted: '신청이 정상 접수되었습니다.',
    pending_payment: '결제 연동 예정 단계입니다.',
    pending_provisioning: '개통 준비 중입니다. 도착 후 개통을 진행하세요.',
    completed: '개통이 완료되어 데이터를 이용할 수 있습니다.',
    failed: '신청 처리에 실패했습니다. 다시 시도해 주세요.',
    draft: '작성 중인 신청입니다.',
  },
  activate: {
    title: '개통 안내',
    subtitle: '현지 도착 후 아래 순서대로 진행하면 데이터가 켜집니다.',
    iphone: 'iPhone',
    android: 'Android',
    steps: [
      {
        title: 'eSIM 설치 (QR 스캔)',
        desc: '신청 시 받은 QR을 카메라로 스캔해 설치하세요. (USIM은 카드를 단말에 삽입)',
      },
      { title: '요금제 추가', desc: '“eSIM 추가”를 눌러 안내에 따라 설치를 완료합니다.' },
      { title: '데이터 로밍 켜기', desc: 'LOTTE ROAMING 회선의 데이터 로밍을 켜면 개통됩니다.' },
    ],
    done: '개통 완료 처리',
    doneNote: '도착 후 위 단계를 마치면 데이터를 이용할 수 있습니다. (시연: 버튼으로 완료 처리)',
    help: '도움이 필요하신가요?',
  },
  empty: { generic: '표시할 내용이 없습니다.' },
  error: {
    generic: '문제가 발생했습니다. 잠시 후 다시 시도해 주세요.',
    notFound: '요청하신 정보를 찾을 수 없습니다.',
    submit: '신청 접수에 실패했습니다. 다시 시도해 주세요.',
  },
  direction: {
    question: '어디로 가시나요?',
    inbound: {
      tab: '한국으로 오시나요?',
      sub: '한국 여행의 시작부터 쇼핑·관광·투어까지 롯데 로밍 하나로 더 편하게.',
      cta: '한국 상품·혜택 보기',
      areaTitle: '한국 어디에 머무시나요?',
    },
    outbound: {
      tab: '해외로 가시나요?',
      sub: '해외에서도 로밍은 기본, 롯데와 함께 쇼핑·관광 혜택까지. 귀국 후엔 조건에 따라 L.POINT 적립도.',
      cta: '내 여행지 로밍 찾기',
      areaTitle: '어느 나라로 가시나요?',
    },
    productsTitle: '추천 로밍 상품',
    partnersTitle: '롯데 · L.POINT 혜택',
    partnerNote: '혜택은 제휴처에 따라 다르며 제공 예정입니다. L.POINT 회원 연동 시 제공 가능합니다.',
    pickArea: '여행지를 선택하면 추천 상품을 보여드려요.',
    categories: {
      shopping: '쇼핑',
      tour: '관광·투어',
      stay: '숙박·레저',
      dutyfree: '면세·공항',
      lpoint: 'L.POINT',
    },
    guideTitle: '추천',
    koreaGuideTitle: '한국 여행, 이렇게 즐기세요',
    koreaGuideSub: '로밍과 함께하면 좋은 롯데 숙박·관광·쇼핑 추천.',
    guideNote: '머무는 지역 근처의 롯데·L.POINT 제휴 추천입니다. 혜택은 제공 예정입니다.',
    guideCategories: { stay: '숙박', tour: '관광', shopping: '쇼핑', food: '맛집' },
    reviewsTitle: '여행자 후기',
    reviewsUnit: '개 후기',
    reviewVerified: '실제 이용 후기',
    reviewTranslated: '번역됨',
    reviewTranslating: '번역 중…',
    reviewShowOriginal: '원문 보기',
    reviewShowTranslation: '번역 보기',
    reviewWrite: '후기 작성',
    reviewFormTitle: '여행 후기 남기기',
    reviewRating: '별점',
    reviewText: '후기 내용',
    reviewTextPh: '로밍과 여행은 어떠셨나요?',
    reviewName: '표시 이름',
    reviewNamePh: '예) 지현',
    reviewPhoto: '분위기 선택',
    reviewSubmit: '후기 등록',
    swipeHint: '밀어서 넘겨보세요',
    brandTag: 'L.POINT',
  },
  catalog: {
    partners: {
      'in-shopping': { title: '한국 롯데 쇼핑', desc: '롯데백화점·마트·월드몰 제휴 할인 — L.POINT 회원 대상 제공 예정' },
      'in-tour': { title: '관광·투어', desc: '롯데월드·서울스카이 등 제휴 명소 혜택 — 제공 예정' },
      'in-stay': { title: '숙박·레저', desc: '롯데호텔·시그니엘 숙박 혜택 — 제공 예정' },
      'in-dutyfree': { title: '롯데면세점', desc: '시내·매장 면세 혜택 — 일부 제휴처 대상, 제공 예정' },
      'in-lpoint': { title: 'L.POINT 멤버십', desc: '체류 중 제휴처에서 L.POINT 적립·사용 — 멤버십 연동 시 제공 가능' },
      'out-shopping': { title: '해외 쇼핑', desc: '롯데·연계사 해외 쇼핑 혜택 — 제공 예정' },
      'out-tour': { title: '해외 관광·투어', desc: '여행지 제휴 관광·명소 혜택 — 제공 예정' },
      'out-stay': { title: '숙박·교통·공항', desc: '해외 제휴 호텔·공항·교통 혜택 — 제공 예정' },
      'out-dutyfree': { title: '면세·공항 수령', desc: '롯데면세점 온라인 주문·공항 수령 — 일부 제휴처 대상, 제공 예정' },
      'out-lpoint': { title: '귀국 후 L.POINT', desc: '로밍 이용 완료 후 조건에 따라 L.POINT 적립 — 조건 적용' },
    },
    lottePerks: {
      'kr-signiel': { title: '시그니엘 서울', desc: '롯데월드타워의 럭셔리 숙박 — 회원 혜택 제공 예정' },
      'kr-world': { title: '롯데월드 · 서울스카이', desc: '테마파크·전망대 제휴 혜택 — 제공 예정' },
      'kr-dept': { title: '롯데백화점', desc: '전국 플래그십 매장 — 회원 할인 제공 예정' },
      'kr-duty': { title: '롯데면세점', desc: '시내·공항 면세 — 혜택 제공 예정' },
      'jp-stay': { title: '롯데 제휴 호텔', desc: '도쿄·오사카 제휴 숙박 — 제공 예정' },
      'jp-shop': { title: '쇼핑·다이닝', desc: '롯데·제휴사 쇼핑 혜택 — 제공 예정' },
      'jp-duty': { title: '면세 공항 수령', desc: '롯데면세점 온라인 주문 + 공항 수령 — 제공 예정' },
      'cn-duty': { title: '롯데면세점', desc: '시내·온라인 면세 — 혜택 제공 예정' },
      'cn-shop': { title: '제휴 쇼핑', desc: '롯데·제휴사 쇼핑 — 제공 예정' },
      'cn-stay': { title: '제휴 호텔', desc: '제휴 숙박 — 제공 예정' },
      'as-duty': { title: '롯데면세점', desc: '시내·공항 면세 — 혜택 제공 예정' },
      'as-shop': { title: '제휴 쇼핑', desc: '롯데·제휴사 쇼핑 — 제공 예정' },
      'as-tour': { title: '관광·명소', desc: '제휴 명소 혜택 — 제공 예정' },
      'sea-hotel': { title: '롯데호텔 하노이 · 사이공', desc: '베트남 랜드마크 숙박 — 회원 혜택 제공 예정' },
      'sea-dept': { title: '롯데백화점 · 마트', desc: '하노이·제휴 매장 — 할인 제공 예정' },
      'sea-duty': { title: '롯데면세점', desc: '다낭·제휴 면세 — 혜택 제공 예정' },
      'us-palace': { title: '롯데 뉴욕 팰리스', desc: '맨해튼 미드타운의 아이코닉 호텔 — 회원 혜택 제공 예정' },
      'us-seattle': { title: '롯데호텔 시애틀', desc: '시애틀 다운타운 랜드마크 — 혜택 제공 예정' },
      'us-duty': { title: '면세 · 제휴', desc: '롯데면세점 온라인 + 제휴 혜택 — 제공 예정' },
      'eu-duty': { title: '롯데면세점', desc: '온라인 주문·공항 수령 — 혜택 제공 예정' },
      'eu-shop': { title: '제휴 쇼핑', desc: '롯데·제휴사 쇼핑 혜택 — 제공 예정' },
      'eu-stay': { title: '제휴 호텔', desc: '유럽 제휴 숙박 — 제공 예정' },
      'oc-guam': { title: '롯데호텔 괌', desc: '투몬베이 비치프런트 숙박 — 회원 혜택 제공 예정' },
      'oc-duty': { title: '롯데면세점 괌', desc: '투몬 플래그십 면세 — 혜택 제공 예정' },
      'oc-tour': { title: '아일랜드 투어·레저', desc: '제휴 투어·액티비티 혜택 — 제공 예정' },
      'w-stay': { title: '롯데호텔 & 리조트', desc: '전 세계 롯데 체인 — 회원 혜택 제공 예정' },
      'w-duty': { title: '롯데면세점', desc: '온라인 주문 + 공항 수령 — 혜택 제공 예정' },
      'w-lpoint': { title: '귀국 후 L.POINT', desc: '귀국 후 조건에 따라 L.POINT 적립 — 조건 적용' },
    },
    products: {
      korea: { name: '대한민국', tagline: '한국 여행용 선불 데이터 — 데일리 또는 한 통.' },
      japan: { name: '일본', tagline: '일본 여행용 선불 데이터. 도착 즉시 연결.' },
      asia: { name: '아시아', tagline: '중국·대만·동남아 전역 선불 데이터.' },
      europe: { name: '유럽', tagline: '유럽 전역 한 상품 — 데일리 또는 한 통.' },
      americas: { name: '북미', tagline: '미국·캐나다 전역 선불 데이터.' },
      oceania: { name: '오세아니아', tagline: '호주·괌·사이판 선불 데이터.' },
      global: { name: '글로벌', tagline: '전 세계 한 상품 — 여러 나라 일정에 딱.' },
    },
    benefits: {
      point: { title: 'L.POINT 적립', desc: '신청 시 L.POINT 멤버십 연동, 적립 혜택 안내 예정' },
      install: { title: '즉시 개통', desc: 'eSIM은 QR 스캔으로 바로 개통' },
      nocontract: { title: '약정 없음', desc: '선불형 · 해지 위약금 없음' },
      '5g': { title: '5G 지원', desc: '현지 5G 지원 지역에서 5G 이용' },
      support: { title: '24시간 지원', desc: '현지에서도 24시간 고객 지원' },
      welcome: { title: '웰컴 기프트', desc: '신규 신청 제휴 혜택 안내 예정' },
    },
    notices: {
      throttle:
        '일일 제공량 소진 후에는 다음 날 00:00(현지시간) 충전 전까지 저속(최대 1Mbps)으로 무제한 이용됩니다.',
      volume: '종량제는 유효기간 내 데이터를 자유롭게 사용하며, 모두 소진하면 충전이 필요합니다.',
      esim: 'eSIM은 eSIM 지원 단말에서만 사용할 수 있습니다(iPhone XS 이상 및 주요 안드로이드).',
      usim_deliver: 'USIM 배송은 신청 후 1~2일 소요되며, 출국 전 수령이 필요합니다.',
      coverage: '현지 통신 환경 및 이용 지역에 따라 속도가 달라질 수 있습니다.',
      price: '요금 및 혜택은 확정 후 별도 안내되며, 현재 화면의 금액은 예시 표기(₩—)입니다.',
    },
    areaGuides: {
      'KR-SEL': {
        tagline: '잠실·명동·한강 일대에서 머물고, 쇼핑하고, 즐기세요.',
        highlights: {
          'sel-stay': { title: '시그니엘 서울', desc: '롯데월드타워의 럭셔리 호텔 — L.POINT 회원 혜택 제공 예정' },
          'sel-tour': { title: '서울스카이 · 롯데월드', desc: '국내 최고층 전망대와 테마파크 제휴 혜택 — 제공 예정' },
          'sel-shopping': { title: '롯데백화점 명동', desc: '플래그십 매장과 롯데면세점 — 회원 할인 제공 예정' },
        },
      },
      'KR-PUS': {
        tagline: '해운대·광복동 일대의 해변과 해산물, 쇼핑까지.',
        highlights: {
          'pus-stay': { title: '롯데호텔 부산', desc: '서면·해운대 인접 숙박 — 회원 혜택 제공 예정' },
          'pus-shopping': { title: '롯데백화점 광복점', desc: '옥상정원이 있는 바닷가 백화점 — 혜택 제공 예정' },
          'pus-tour': { title: '해운대 · 광안리', desc: '해안 제휴 명소·투어 혜택 — 제공 예정' },
        },
      },
      'KR-CJU': {
        tagline: '제주의 자연과 리조트, 면세 쇼핑까지.',
        highlights: {
          'cju-stay': { title: '롯데호텔 제주', desc: '중문 리조트 숙박 — 회원 혜택 제공 예정' },
          'cju-dutyfree': { title: '롯데면세점 제주', desc: '출국 전 면세 픽업 — 혜택 제공 예정' },
          'cju-tour': { title: '제주 자연 투어', desc: '섬 곳곳 제휴 투어·명소 혜택 — 제공 예정' },
        },
      },
      'KR-ICN': {
        tagline: '공항과 환승, 한국의 관문.',
        highlights: {
          'icn-pickup': { title: '롯데면세점 공항 픽업', desc: '온라인 주문 후 인천 T1/T2 수령 — 혜택 제공 예정' },
          'icn-stay': { title: '공항 인근 숙박', desc: '이른 출발·환승을 위한 제휴 호텔 — 제공 예정' },
        },
      },
      'KR-GYG': {
        tagline: '수도권 테마파크·아울렛과 근교 나들이.',
        highlights: {
          'gyg-shopping': { title: '롯데 프리미엄 아울렛', desc: '경기권 브랜드 아울렛 — 회원 혜택 제공 예정' },
          'gyg-tour': { title: '테마파크·근교 여행', desc: '서울 근교 제휴 명소 혜택 — 제공 예정' },
        },
      },
      'KR-GWO': {
        tagline: '강원의 산과 바다, 리조트.',
        highlights: {
          'gwo-stay': { title: '리조트·레저 숙박', desc: '해안·슬로프 인근 제휴 리조트 — 제공 예정' },
          'gwo-tour': { title: '해안·산악 투어', desc: '강원 전역 제휴 투어 혜택 — 제공 예정' },
        },
      },
      'KR-GYB': {
        tagline: '신라 천년 고도의 역사와 유산.',
        highlights: {
          'gyb-tour': { title: '유적 투어', desc: '경주 제휴 유적지·투어 혜택 — 제공 예정' },
          'gyb-stay': { title: '유적지 인근 숙박', desc: '역사지구 인근 제휴 숙박 — 제공 예정' },
        },
      },
      'KR-ETC': {
        tagline: '한국 곳곳을 다니나요? 어디서든 함께합니다.',
        highlights: {
          'etc-lpoint': { title: '전국 L.POINT', desc: '전국 롯데 제휴처에서 L.POINT 적립·사용 — 멤버십 연동 시' },
          'etc-stay': { title: '롯데호텔 & 리조트', desc: '전국 주요 도시 숙박 — 회원 혜택 제공 예정' },
          'etc-dutyfree': { title: '롯데면세점', desc: '시내·공항 면세 — 혜택 제공 예정' },
        },
      },
    },
    reviews: {
      'rv-in-1': {
        tag: '코리아 데일리 · 서울',
        text: '비행 전에 eSIM QR만 스캔해두니 인천 도착하자마자 바로 연결됐어요. 롯데백화점에서 L.POINT도 썼습니다!',
      },
      'rv-in-2': {
        tag: '코리아 eSIM 데일리 · 부산',
        text: '해운대 해변에서도 현지망이 빨랐어요. 설정 2분이면 끝, 약정 해지 걱정도 없었습니다.',
      },
      'rv-in-3': {
        tag: '코리아 종량제 · 제주',
        text: '여행 내내 하나의 데이터로 쓰니 제주에 딱이었어요. 지도·번역 어디서나 잘 됐습니다.',
      },
      'rv-in-4': {
        tag: '코리아 USIM · 서울',
        text: '공항 카운터에서 USIM 픽업했어요. 과정이 깔끔했고 면세 혜택 알림도 좋았습니다.',
      },
      'rv-out-1': { tag: '재팬 데일리 · 오사카' },
      'rv-out-2': { tag: '유럽 데일리 · 파리' },
      'rv-out-3': { tag: '아시아 데일리 · 방콕' },
      'rv-out-4': { tag: '오세아니아 데일리 · 괌' },
    },
    faq: {
      inbound: [
        {
          q: 'eSIM과 USIM은 어떻게 다른가요?',
          a: 'eSIM은 QR 코드로 즉시 설치하는 디지털 SIM으로 실물 카드가 없습니다. USIM은 실물 카드로, 출국 전 배송으로 받아 단말에 끼워 사용합니다.',
        },
        {
          q: '데일리와 종량제는 무엇이 다른가요?',
          a: '데일리는 매일 일정 용량이 새로 충전되며 소진 후에는 저속으로 무제한 이용됩니다. 종량제는 유효기간 동안 하나의 데이터를 자유롭게 사용하는 방식입니다.',
        },
        {
          q: '한국에서 롯데·L.POINT 혜택은 어떻게 받나요?',
          a: '신청 단계에서 L.POINT 멤버십으로 로그인하면 제휴 혜택(쇼핑·관광·숙박·면세)이 연동됩니다. 구체적인 혜택은 제휴처에 따라 다르며 제공 예정입니다.',
        },
        {
          q: '개통은 언제, 어떻게 하나요?',
          a: '한국 도착 후 데이터 로밍을 켜면 개통됩니다. eSIM은 신청 시 받은 QR을 설치한 뒤 도착지에서 활성화하면 됩니다.',
        },
      ],
      outbound: [
        {
          q: '여행지와 상품은 어떻게 고르나요?',
          a: '먼저 여행 국가를 선택하면 해당 국가에서 이용 가능한 로밍 상품으로 필터링되고, 일정에 맞게 데일리/종량제를 고르면 됩니다.',
        },
        {
          q: '데일리와 종량제는 무엇이 다른가요?',
          a: '데일리는 매일 일정 용량이 새로 충전되며 소진 후에는 저속으로 무제한 이용됩니다. 종량제는 유효기간 동안 하나의 데이터를 자유롭게 사용하는 방식입니다.',
        },
        {
          q: '해외 로밍 이용 시 L.POINT 적립이 되나요?',
          a: '로밍 이용 완료 후 조건에 따라 귀국 시 L.POINT 적립 혜택이 제공될 수 있습니다. 적립률·조건은 추후 안내 예정입니다.',
        },
        {
          q: '해외에서 개통은 어떻게 하나요?',
          a: '도착 후 데이터 로밍을 켜면 개통됩니다. eSIM은 신청 시 받은 QR을 설치한 뒤 도착지에서 활성화하면 됩니다.',
        },
      ],
    },
  },
  footer: {
    affiliate: '롯데 로밍',
    company: {
      name: '롯데멤버스(주)',
      rows: [
        ['대표이사: 박종남'],
        ['주소: 04511 서울특별시 중구 통일로2길 16, 14층'],
        ['사업자등록번호: 104-86-58491', '통신판매업 신고: 2015-서울 중구-1231'],
        ['호스팅 서비스 사업자: 롯데이노베이트주식회사'],
      ],
    },
    intermediary:
      '롯데멤버스는 통신판매중개자이며 통신판매의 당사자가 아닙니다. 따라서 롯데멤버스는 상품·거래정보 및 거래에 대하여 책임을 지지 않습니다.',
    language: '언어',
    links: ['제휴안내', '고객센터', '이용약관'],
    links2: ['개인정보처리방침', '분쟁처리'],
    demoNote: '시연용 MVP — 확정되지 않은 요금·혜택·약관은 추후 별도 안내됩니다.',
  },
}

export default ko
