import type { Content } from './en'

type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] }

// 中文 — prominent strings; the rest fall back to English.
const zh: DeepPartial<Content> = {
  brand: { affiliate: '乐天漫游' },
  nav: { home: '首页', browse: '旅行', applications: '我的申请', login: '登录', myAccount: '账户' },
  cta: {
    browse: '查看韩国套餐',
    global: '前往其他国家？全球套餐',
    selectDestination: '选择目的地',
    apply: '申请',
    viewDetail: '查看详情',
    continue: '继续',
    next: '下一步',
    submit: '提交申请',
    toComplete: '提交申请',
    goHome: '返回首页',
    viewApplication: '查看申请',
    activate: '开通指南',
    retry: '重试',
  },
  home: {
    heroEyebrow: '韩国旅行数据',
    heroTitle: '你的韩国，\n即刻连接。',
    heroDesc: '面向访韩旅客的预付 eSIM 与 USIM。几分钟开通、无合约，还有 L.POINT 会员礼遇。',
    plansTitle: '韩国数据套餐',
    plansDesc: '选择套餐，几分钟完成申请。',
    benefitsTitle: 'L.POINT 会员礼遇',
    benefitsDesc: '申请 LOTTE ROAMING 即享以下礼遇。',
    destinationsMore: '查看全部',
    howTitle: '使用方法',
    howSteps: [
      { title: '选择套餐', desc: '每日或总量，按行程选择。' },
      { title: '选择选项', desc: 'eSIM 或 USIM、天数与网络。' },
      { title: '填写信息', desc: '领取方式与个人信息。' },
      { title: '抵达后开通', desc: '打开数据即可使用。' },
    ],
    faqTitle: '常见问题',
  },
  browse: {
    title: '韩国数据套餐',
    subtitle: '面向访韩旅客的预付 eSIM 与 USIM。',
    resultCount: (n: number) => `${n} 个套餐`,
    empty: '暂无可用套餐。',
    koreaName: '韩国',
  },
  product: {
    perDay: '每日',
    days: '天数',
    total: '总流量',
    validity: '有效期',
    sim: 'SIM',
    network: '网络',
    benefitsTitle: '包含礼遇',
    noticeTitle: '注意事项',
    priceNote: '示例资费 · 因天数/流量而异。',
    perDayShort: '天',
    unlimited: '无限量',
    daysUnit: (n: number) => `${n} 天`,
    gbPerDay: (n: number) => `每日 ${n}GB`,
    totalGb: (n: number) => `共 ${n}GB`,
  },
  sim: { esimDesc: '扫码即装 · 无实体卡', usimDesc: '实体卡 · 出发前配送' },
  network: { roaming: '漫游网络', local: 'SKT 本地网络' },
  receive: {
    esim_qr: 'eSIM 二维码（邮件发送）',
    delivery: '快递配送（1–2 天）',
    airport_pickup: '机场领取（仁川 T1/T2）',
  },
  steps: ['登录', '信息', '确认', '完成'],
  signin: {
    title: '登录或注册',
    subtitle: '一键继续——新账户即开通 L.POINT 会员。',
    or: '或',
    providers: {
      kakao: '使用 Kakao 继续',
      line: '使用 LINE 继续',
      google: '使用 Google 继续',
      apple: '使用 Apple 继续',
      wechat: '使用微信继续',
      email: '使用邮箱继续',
    },
    terms: '我同意条款与隐私政策（必填）',
    push: '接收到达指南与礼遇通知',
    marketing: '营销信息（可选）',
    termsRequired: '请同意必填条款。',
    lpoint: '创建账户同时会为你开通 L.POINT 会员，享旅行礼遇。',
  },
  applicant: {
    title: '填写申请信息',
    subtitle: '开通与通知需要申请人信息。',
    name: '姓名',
    email: '邮箱',
    phone: '手机号',
    travelStart: '出发日',
    travelEnd: '返程日',
    receiveTitle: '领取方式',
    address: '配送地址',
    required: '此项为必填。',
    invalidEmail: '邮箱格式不正确。',
    invalidPhone: '请输入 10–11 位数字。',
    invalidDate: '返程日需不早于出发日。',
    addressRequired: '请填写 USIM 配送地址。',
  },
  confirm: {
    title: '确认申请',
    subtitle: '确认信息并提交申请。',
    destination: '目的地',
    product: '套餐',
    options: '选项',
    applicant: '申请人',
    period: '旅行日期',
    receive: '领取方式',
    agree: '我已确认申请内容与注意事项并同意。',
    agreeRequired: '需同意后继续。',
    paymentNote: '支付将于后续接入，目前以申请受理进行。',
    processing: '正在提交…',
    estimatedTotal: '预计金额',
  },
  complete: {
    title: '申请已受理',
    subtitle: '查看申请与后续指引。',
    refLabel: '申请编号',
    esimNext: 'eSIM 二维码已发送至邮箱。抵达后打开数据漫游即可开通。',
    usimNext: 'USIM 将配送至你的地址（1–2 天），请在出发前收取。',
    noticeTitle: '注意事项',
    summaryTitle: '申请摘要',
  },
  applications: {
    title: '我的申请',
    subtitle: '查看漫游申请状态。',
    empty: '暂无申请记录。',
    emptyCta: '去看漫游套餐',
    detailTitle: '申请详情',
    appliedAt: '申请日',
  },
  status: {
    submitted: '已受理',
    pending_payment: '待支付',
    pending_provisioning: '开通准备',
    completed: '已开通',
    failed: '申请失败',
    draft: '草稿',
  },
  activate: {
    title: '开通指南',
    subtitle: '抵达后按以下步骤即可开通。',
    steps: [
      { title: '安装 eSIM（扫码）', desc: '用相机扫描收到的二维码安装。（USIM 请插入卡片）' },
      { title: '添加套餐', desc: '点击“添加 eSIM”并按提示操作。' },
      { title: '打开数据漫游', desc: '为 LOTTE ROAMING 线路打开数据漫游。' },
    ],
    done: '标记为已开通',
    help: '需要帮助？',
  },
  direction: {
    reviewTranslated: '已翻译',
    reviewTranslating: '翻译中…',
    reviewShowOriginal: '查看原文',
    reviewShowTranslation: '查看翻译',
  },
}

export default zh
